sudo: false

language: go

go:
  - 1.8.x

script:
  - GOPATH=$(pwd) go test -v -coverprofile=coverage.txt -covermode=atomic github.com/mdirkse/i3wp

after_success:
  - bash <(curl -s https://codecov.io/bash)
